services:
  db:
    image: postgres:16.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
